### PR TITLE
Fix/refactor es6

### PR DESCRIPTION
**Pull request by adebsa2401**
In this project, we refactor the [Awesome-Books project](https://github.com/adebsa2401/Awesome-Books) by using ES6 rules. Functions and methods have been refactored into arrow functions. Use of `let` and `const` keywords has been reviewed.

### CODE REVIEW

**Review by Bondok6 — COMMENTED** [review]
## Hi @adebsa2401 🙋‍♂️, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

- [ ] You have submitted a project, that has Linter errors `Eslint`, Kindly fix them 
1. Linter result should be green, this means that the last commit have a green check mark (✅)

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by adebsa2401** [comment]
Hi @Bondok6 . Thanks for your review.
But actually the linters issues that are raised come from the luxon module file that I downloaded. So am I allowed to edit that file?

**Comment by Bondok6** [comment]
Hi @adebsa2401 🙋‍♂️
I think it's ok if you disabled the linter for this file using inline comment `// eslint-disable`

**Review by Bondok6 — APPROVED** [review]
# STATUS: APPROVED :green_circle: :clap: 

## Hi @adebsa2401 🙋‍♂️, 
Your project is complete!  There is nothing else to say other than... Great job 👏 
Congratulations! 🎉 

TO HIGHLIGHT:

- Great job using ES6 Features and Arrow Functions ✅
- Your project is professional ✅
- Your repo is professional ✅
- Well structured files ✅
- Professional README.md file 💯


Now you can merge this branch and move on :1st_place_medal: 
HAPPY CODING AND GOOD LUCK WITH THE COMMING ONES :crossed_fingers: :four_leaf_clover: 




Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
